# Generated by Django 4.2.7 on 2023-12-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='garafe',
            new_name='garage',
        ),
    ]
